name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: test conditions
        if: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: echo "Skipping the deployment and tagging"
      - name: test actor
        env:
          ACTOR: ${{ toJson(github.actor) }}
        run: echo "$ACTOR"  
        - name: test commit urls
        env:
          COMMIT_URLS: ${{ toJson(github.event.commits.*.url) }}
        run: echo "$COMMIT_URLS"
        - name: test app url
        env:
          APP_URL: ${{ https://apndx-pokedex.herokuapp.com/ }} 
        run: echo To "$APP_URL" by "$ACTOR"
